
all:
	$(MAKE) -C common
	$(MAKE) -C libxrdp
	$(MAKE) -C xrdp
	$(MAKE) -C xup
	$(MAKE) -C vnc

clean:
	$(MAKE) -C common clean
	$(MAKE) -C libxrdp clean
	$(MAKE) -C xrdp clean
	$(MAKE) -C xup clean
	$(MAKE) -C vnc clean

install:
	$(MAKE) -C common install
	$(MAKE) -C libxrdp install
	$(MAKE) -C xrdp install
	$(MAKE) -C xup install
	$(MAKE) -C vnc install
