
all:
	$(MAKE) -C common
	$(MAKE) -C libxrdp
	$(MAKE) -C xrdp
	$(MAKE) -C xup
	$(MAKE) -C vnc
	$(MAKE) -C sesman
	$(MAKE) -C keygen

clean:
	$(MAKE) -C common clean
	$(MAKE) -C libxrdp clean
	$(MAKE) -C xrdp clean
	$(MAKE) -C xup clean
	$(MAKE) -C vnc clean
	$(MAKE) -C sesman clean
	$(MAKE) -C keygen clean

install:
	$(MAKE) -C common install
	$(MAKE) -C libxrdp install
	$(MAKE) -C xrdp install
	$(MAKE) -C xup install
	$(MAKE) -C vnc install
	$(MAKE) -C sesman install
	$(MAKE) -C keygen install
